version: "3.8"
services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}_nginx
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/srv/www/todo
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/var/logs/nginx:/var/log/nginx
    depends_on:
      - php-fpm
      - db
    networks:
      app-network:
        ipv4_address: 10.10.0.2

  php-fpm:
    build:
      context: .
      dockerfile: ./conf/php-fpm/Dockerfile
    restart: always
    container_name: ${APP_NAME}_php-fpm
    tty: true
    volumes:
      - ./app:/srv/www/todo
      - ./conf/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      app-network:
        ipv4_address: 10.10.0.3

  db:
    image: postgres
    restart: always
    container_name: ${APP_NAME}_db
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      app-network:
        ipv4_address: 10.10.0.7

volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.0.0/16
         gateway: 10.10.0.1
